local:
  log: medialog_local.log
  port: 8080
  database:
    username: medialog
    password: medialog
    url: localhost
    port: 3306
    database_name: medialog_prod
    admin_email: admin@medialog.dlib.nyu.edu
  https_keys:
    certificate: path/to/cert
    key: path/to/key
